# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Francisco Espinoza
email: francisco@espinz.com
description: >- # this means to ignore newlines until "baseurl:"
  Another computer related site. You will find some of my notes here.
  Programmimg, Networking, and other random stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://espinz.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  espinz
footer_title: "Contact Information"

collections_dir: my_collections
collections:
    notes:
        output: true
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-archives

show_excerpts: true

include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
 # exclude:
  #   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#header_pages:
#- _pages/about.md
#- _pages/archives.md
#- _pages/articles.md
